### ISSUE TITLE
`Error: notImplemented` when calling createTranscript

### ISSUE THREAD

**Issue by mepc36** [voiceflow/demo-react-chat#8]
Hi, I ported this @voiceflow/demo-react-chat app found [here](https://github.com/voiceflow/demo-react-chat) from vite to Next.js. I then migrated it into my app. Currently, it's throwing this error:

```
index.es.js:10276 Uncaught (in promise) Error: not implemented
    at _D.createTranscript (index.es.js:10276:1)
    at DD.createTranscript (index.es.js:10364:1)
    at B (index.es.js:14940:1)
    at Object.reply (index.es.js:14955:1)
    at handleSend (Demo.js:37:15)
    at onSend (index.es.js:9535:1)
    at onKeyPress (index.es.js:9454:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at eval (react-dom.development.js:9288:1)
    at batchedUpdates$1 (react-dom.development.js:26140:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js:6430:1)
```

It happens whenever I send a message to the chatbot. It seems like maybe a typing error?

This is my @voiceflow/react-chat version:

`"@voiceflow/react-chat": "^1.46.1"`

I will report back with more info.

This is the `createTranscript` function throwing the error. Not sure why it's calling this function if it's explicitly not been implemented:

```
  async feedback() {
    return Promise.reject(new Error("not implemented"));
  }
  getPublishing() {
    return Promise.reject(new Error("not implemented"));
  }
  createTranscript() {
    return Promise.reject(new Error("not implemented"));
  }
```

This happened when I was testing the bot created by importing the example.vf file found in this project's root directory, so it should work.

**Comment by mepc36** [comment]
Here's a picture of the problem
![Screenshot 2023-10-04 at 2 02 11 PM](https://github.com/voiceflow/demo-react-chat/assets/16109633/16877749-ad3a-4f32-a542-147dad1b73b8)

**Comment by jawwadturabi** [comment]
Getting the same error

**Comment by tloriato** [comment]
Hey! @jawwadturabi and @mepc36 did you find a solution?
